// GitHub agent: makes the change in a real repo and opens a draft pull request.
//
//   1. Clone     a fresh shallow copy of the repo (never a user's working copy)
//   2. Graph     look up the stored knowledge graph for this repo (if available)
//                to add affected-node context to the PR description
//   3. Edit      core/scanner/ts-rename.mjs: the TypeScript compiler's own rename,
//                plus `keyof` string keys and docs that name the field
//   4. Check     no new type errors in any file that mentions the old name
//   5. Preview   git diff, returned to the browser (dry run stops here)
//   6. Push      a new branch systemdna/<change> (never the default branch)
//   7. PR        a DRAFT pull request with the impact report as its description
//
// Credentials come from lib/server/github-auth.ts: a 1-hour GitHub App token for
// this one repo, or GITHUB_TOKEN when no app is set up. The token is sent as an
// HTTP header, never put in a URL, a git remote or a log line.

import "server-only";
import path from "node:path";
import { existsSync } from "node:fs";
import { LIMITS, run, validateGitInput, withWorkspace } from "@/lib/server/ingest";
import { listRepos, getRepo } from "@/lib/server/graph-store";
import { computeImpact } from "@/lib/impact";
import { credentialsFor, githubApi, githubMode, scrub } from "@/lib/server/github-auth";

export type AgentEvent =
  | { type: "progress"; step: string; detail: string }
  | { type: "preview"; files: { file: string; count: number }[]; docs: { file: string; count: number }[]; locations: number; stringKeys: number; diff: string; diffTruncated: boolean }
  | { type: "done"; dryRun: true }
  | { type: "done"; dryRun: false; pr: { url: string; number: number; branch: string; base: string } }
  | { type: "error"; message: string; newErrors?: { file: string; line: number; message: string }[] };

type Emit = (e: AgentEvent) => void;

export interface PullRequestInput {
  url: string;
  ref?: string;
  /** "Type.field" */
  field: string;
  to: string;
  changeId: string;
  title: string;
  body: string;
  dryRun: boolean;
  /** Optional: id of the stored repo. When provided, the agent uses the knowledge graph
   *  to add wave/impact context to the PR description automatically. */
  repoId?: string;
}

/**
 * Find the stored knowledge-graph repo entry that matches a git URL.
 * Returns null if no matching repo is found locally.
 */
async function findStoredRepo(url: string, repoId?: string) {
  if (repoId) return getRepo(repoId);
  const all = await listRepos();
  const match = all.find((r) => r.url === url);
  if (!match) return null;
  return getRepo(match.id);
}

/**
 * Build a markdown section describing the impact from the knowledge graph.
 * Appended to the PR body when a graph is available.
 */
function graphImpactMarkdown(
  field: string,
  to: string,
  result: ReturnType<typeof computeImpact>,
): string {
  const lines: string[] = [
    "## Knowledge graph impact",
    "",
    `SystemDNA scanned this repository and traced every dependency of \`${field}\`.`,
    "",
    `| Metric | Value |`,
    `| --- | --- |`,
    `| Components affected | ${result.items.length} |`,
    `| Fix waves | ${result.waveCount} |`,
    `| Dangling references before fix | ${result.danglingRefs} |`,
    `| Computation time | ${result.computedMs} ms |`,
    "",
  ];

  if (result.business.length > 0) {
    lines.push("**Business processes affected:**");
    for (const b of result.business) {
      lines.push(`- ${b.name}${b.owner ? ` (owner: ${b.owner})` : ""} — ${b.severity}`);
    }
    lines.push("");
  }

  if (result.grep.missed.length > 0) {
    lines.push(
      `**${result.grep.missed.length} file(s) that grep for \`${field}\` would miss** (found via the compiler graph, not text search):`,
    );
    for (const f of result.grep.missed.slice(0, 10)) lines.push(`- \`${f}\``);
    if (result.grep.missed.length > 10) lines.push(`- … and ${result.grep.missed.length - 10} more`);
    lines.push("");
  }

  lines.push(
    "_Impact report generated by [SystemDNA](https://github.com/pujarachchh-intuitive/AIGarage). " +
      "Graph source: parser (TypeScript language service). " +
      `Renamed \`${field}\` → \`${to}\`._`,
  );
  return lines.join("\n");
}

const MAX_DIFF = 200_000;

/** git -c option that sends the token as a header for github.com only. */
function authConfig(token: string | undefined): string[] {
  if (!token) return [];
  const basic = Buffer.from(`x-access-token:${token}`).toString("base64");
  return ["-c", `http.https://github.com/.extraheader=AUTHORIZATION: basic ${basic}`];
}

export function ownerRepo(url: string) {
  const m = url.match(/^https:\/\/github\.com\/([\w.-]+)\/([\w.-]+?)(\.git)?\/?$/);
  return m ? { owner: m[1], repo: m[2] } : null;
}

function renamePath() {
  const scanner = process.env.SYSTEMDNA_SCANNER || path.resolve(/*turbopackIgnore: true*/ process.cwd(), "../core/scanner/ts-scan.mjs");
  return path.join(/*turbopackIgnore: true*/ path.dirname(scanner), "ts-rename.mjs");
}

export async function runPullRequest(input: PullRequestInput, emit: Emit) {
  const bad = validateGitInput(input.url, input.ref);
  if (bad) throw new Error(bad);
  const target = ownerRepo(input.url);
  if (!target) throw new Error("The GitHub agent works with github.com repositories today.");
  if (!/^[A-Za-z_$][\w$]*\.[A-Za-z_$][\w$]*$/.test(input.field)) throw new Error("Only renames of a TypeScript field (Type.field) are supported today.");
  if (!/^[A-Za-z_$][\w$]*$/.test(input.to)) throw new Error("The new name must be a valid identifier.");
  if (!input.dryRun && githubMode() === "none") throw new Error("Set up the GitHub App (GITHUB_APP_ID and private key) or GITHUB_TOKEN on the server to open pull requests.");
  // Private repos need a token even to clone. For a preview without one, clone anonymously.
  const creds = await credentialsFor(target.owner, target.repo).catch((e: Error) => {
    if (input.dryRun) return null;
    throw e;
  });
  const renameScript = renamePath();
  if (!existsSync(renameScript)) throw new Error(`Rename agent not found at ${renameScript}.`);

  // 2. Look up the stored knowledge graph for this repo (best-effort; does not block).
  let graphImpact = "";
  try {
    const stored = await findStoredRepo(input.url, input.repoId);
    if (stored) {
      const [typeName, fieldName] = input.field.split(".");
      // Find the TSField node that matches the renamed field.
      const node = stored.graph.nodes.find(
        (n) => n.type === "TSField" && n.name === `${typeName}.${fieldName}`,
      ) ?? stored.graph.nodes.find(
        (n) => (n.type === "TSField" || n.type === "Field") && n.name.endsWith(`.${fieldName}`),
      );
      if (node) {
        const report = computeImpact(stored.graph, { node: node.id, change: "rename", to: input.to });
        graphImpact = "\n\n" + graphImpactMarkdown(input.field, input.to, report);
        emit({ type: "progress", step: "graph", detail: `Knowledge graph: ${report.items.length} components affected, ${report.waveCount} wave(s)` });
      }
    }
  } catch {
    // Graph lookup is best-effort; never block the agent.
  }

  return withWorkspace(async (dir) => {
    // 1. Clone.
    emit({ type: "progress", step: "clone", detail: `Cloning ${target.owner}/${target.repo}` });
    const cloneArgs = [...authConfig(creds?.token), "-c", "protocol.file.allow=never", "-c", "core.symlinks=false", "clone", "--depth", "1", "--single-branch", "--no-tags", "--quiet"];
    if (input.ref) cloneArgs.push("--branch", input.ref);
    cloneArgs.push("--", input.url, dir);
    await run("git", cloneArgs, { timeoutMs: LIMITS.cloneMs, env: { GIT_TERMINAL_PROMPT: "0", GIT_LFS_SKIP_SMUDGE: "1" } }).catch((e: Error) => {
      throw new Error(scrub(e.message));
    });

    // 3 and 4. Rename and check.
    emit({ type: "progress", step: "edit", detail: `Renaming ${input.field} to ${input.to} with the TypeScript compiler` });
    let resultLine = "";
    await run(process.execPath, [renameScript, dir, "--field", input.field, "--to", input.to, "--apply"], {
      timeoutMs: LIMITS.scanMs,
      env: { NODE_OPTIONS: "--max-old-space-size=2048" },
      onLine: (l) => {
        resultLine = l;
      },
    }).catch((e: Error) => {
      // Exit code 2 = the agent refused with a reason on stdout.
      if (!resultLine) throw e;
    });
    const result = JSON.parse(resultLine || "{}") as {
      ok: boolean;
      error?: string;
      locations: number;
      stringKeys: number;
      files: { file: string; count: number }[];
      docs: { file: string; count: number }[];
      newErrors: { file: string; line: number; message: string }[];
    };
    if (result.error) throw new Error(result.error);
    if (!result.ok) {
      emit({ type: "error", message: `The rename would add ${result.newErrors.length} type errors, so nothing was changed.`, newErrors: result.newErrors });
      throw Object.assign(new Error("__reported__"), { reported: true });
    }
    emit({ type: "progress", step: "check", detail: `${result.locations} edits in ${result.files.length} code files and ${result.docs.length} docs; no new type errors` });

    // 4. Preview.
    let diff = "";
    await run("git", ["-C", dir, "diff", "--no-color"], { timeoutMs: 60_000, onChunk: (t) => (diff += t) });
    emit({
      type: "preview",
      files: result.files,
      docs: result.docs,
      locations: result.locations,
      stringKeys: result.stringKeys,
      diff: diff.slice(0, MAX_DIFF),
      diffTruncated: diff.length > MAX_DIFF,
    });
    if (input.dryRun) {
      emit({ type: "done", dryRun: true });
      return;
    }

    // 5. Branch, commit, push. Never the default branch.
    const branch = `systemdna/${input.changeId}-${input.field.split(".")[1]}-to-${input.to}`.toLowerCase().replace(/[^a-z0-9/_-]+/g, "-").slice(0, 100);
    emit({ type: "progress", step: "push", detail: `Pushing branch ${branch}` });
    if (!creds) throw new Error("No GitHub credentials for this repo.");
    const repoInfo = await githubApi<{ default_branch: string; permissions?: { push?: boolean } }>(creds.token, `/repos/${target.owner}/${target.repo}`);
    if (creds.mode === "token" && repoInfo.permissions && !repoInfo.permissions.push) {
      throw new Error(`The token cannot push to ${target.owner}/${target.repo}. Give it Contents: write, or fork the repo and connect the fork.`);
    }
    const base = input.ref || repoInfo.default_branch;
    const git = (args: string[]) => run("git", ["-C", dir, ...args], { timeoutMs: LIMITS.cloneMs, env: { GIT_TERMINAL_PROMPT: "0" } }).catch((e: Error) => {
      throw new Error(scrub(e.message));
    });
    await git(["checkout", "-b", branch]);
    await git(["add", "-A"]);
    await git([
      "-c", `user.name=${creds.author.name}`,
      "-c", `user.email=${creds.author.email}`,
      "commit", "--quiet", "--no-verify",
      "-m", input.title,
      "-m", `Rename ${input.field} to ${input.to} across ${result.files.length} code files and ${result.docs.length} docs.\nMade by the SystemDNA GitHub agent with the TypeScript compiler's rename. No new type errors.`,
    ]);
    await run("git", [...authConfig(creds.token), "-C", dir, "push", "--quiet", "origin", `HEAD:refs/heads/${branch}`], { timeoutMs: LIMITS.cloneMs, env: { GIT_TERMINAL_PROMPT: "0" } }).catch((e: Error) => {
      throw new Error(scrub(e.message));
    });

    // 7. Draft pull request.
    emit({ type: "progress", step: "pr", detail: "Opening a draft pull request" });
    const fullBody = (input.body + graphImpact).slice(0, 60_000);
    const pr = await githubApi<{ html_url: string; number: number }>(creds.token, `/repos/${target.owner}/${target.repo}/pulls`, {
      method: "POST",
      body: JSON.stringify({ title: input.title, head: branch, base, body: fullBody, draft: true }),
    });
    emit({ type: "done", dryRun: false, pr: { url: pr.html_url, number: pr.number, branch, base } });
  });
}

/** Streams agent events as newline-delimited JSON. */
export function agentStream(input: PullRequestInput): Response {
  const encoder = new TextEncoder();
  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      const emit: Emit = (e) => controller.enqueue(encoder.encode(JSON.stringify(e) + "\n"));
      try {
        await runPullRequest(input, emit);
      } catch (err) {
        if (!(err as { reported?: boolean }).reported) emit({ type: "error", message: scrub(err instanceof Error ? err.message : "Something went wrong") });
      } finally {
        controller.close();
      }
    },
  });
  return new Response(stream, { headers: { "Content-Type": "application/x-ndjson; charset=utf-8", "Cache-Control": "no-store" } });
}
