// GitHub agent: makes the change in a real repo and opens a draft pull request.
//
//   1. Clone     a fresh shallow copy of the repo (never a user's working copy)
//   2. Graph     look up the stored knowledge graph for this repo (if available)
//                to add affected-node context to the PR description
//   3. Edit      core/scanner/ts-rename.mjs: the TypeScript compiler's own rename,
//                plus `keyof` string keys and docs that name the field
//   4. Check     no new type errors in any file that mentions the old name
//   4b. Review   IBM Bob Inspector reads the diff and gives a verdict (dry run
//                only; optional, never changes the edits)
//   5. Preview   git diff, returned to the browser (dry run stops here)
//   6. Push      a new branch systemdna/<change> (never the default branch)
//   7. PR        a DRAFT pull request with the impact report as its description
//
// Credentials come from lib/server/github-auth.ts: a 1-hour GitHub App token for
// the one repo being changed, or GITHUB_TOKEN when no app is set up. The token is
// sent as an HTTP header, never put in a URL, a git remote or a log line.

import "server-only";
import path from "node:path";
import { existsSync } from "node:fs";
import { extractJson, runBob, scrubBob, TASK_FILE } from "@/lib/server/bob";
import { LIMITS, run, validateGitInput, withWorkspace } from "@/lib/server/ingest";
import { listRepos, getRepo } from "@/lib/server/graph-store";
import { computeImpact } from "@/lib/impact";
import { credentialsFor, githubApi, githubMode, scrub } from "@/lib/server/github-auth";
import type { BobReview } from "@/lib/types";

// Other agents (change-agent.ts) import scrub from here.
export { scrub };

export type AgentEvent =
  | { type: "progress"; step: string; detail: string }
  | { type: "preview"; files: { file: string; count: number }[]; docs: { file: string; count: number }[]; locations: number; stringKeys: number; diff: string; diffTruncated: boolean }
  | { type: "review"; review: BobReview }
  | { type: "done"; dryRun: true }
  | { type: "done"; dryRun: false; pr: { url: string; number: number; branch: string; base: string } }
  | { type: "error"; message: string; newErrors?: { file: string; line: number; message: string }[] };

export type Emit = (e: AgentEvent) => void;

export interface PullRequestInput {
  url: string;
  ref?: string;
  /** "Type.field" */
  field: string;
  to: string;
  changeId: string;
  title: string;
  body: string;
  dryRun: boolean;
  /** Optional: id of the stored repo. When provided, the agent uses the knowledge graph
   *  to add wave/impact context to the PR description automatically. */
  repoId?: string;
}

/**
 * Find the stored knowledge-graph repo entry that matches a git URL.
 * Returns null if no matching repo is found locally.
 */
async function findStoredRepo(url: string, repoId?: string) {
  if (repoId) return getRepo(repoId);
  const all = await listRepos();
  const match = all.find((r) => r.url === url);
  if (!match) return null;
  return getRepo(match.id);
}

/**
 * Build a markdown section describing the impact from the knowledge graph.
 * Appended to the PR body when a graph is available.
 */
function graphImpactMarkdown(
  field: string,
  to: string,
  result: ReturnType<typeof computeImpact>,
): string {
  const lines: string[] = [
    "## Knowledge graph impact",
    "",
    `SystemDNA scanned this repository and traced every dependency of \`${field}\`.`,
    "",
    `| Metric | Value |`,
    `| --- | --- |`,
    `| Components affected | ${result.items.length} |`,
    `| Fix waves | ${result.waveCount} |`,
    `| Dangling references before fix | ${result.danglingRefs} |`,
    `| Computation time | ${result.computedMs} ms |`,
    ...(result.risk ? [`| Risk | ${result.risk.score} / 100 (${result.risk.level}) |`] : []),
    "",
  ];

  if (result.risk?.recommendations.length) {
    lines.push("**Before merging:**");
    for (const t of result.risk.recommendations.slice(0, 5)) lines.push(`- ${t}`);
    lines.push("");
  }

  if (result.business.length > 0) {
    lines.push("**Business processes affected:**");
    for (const b of result.business) {
      lines.push(`- ${b.name}${b.owner ? ` (owner: ${b.owner})` : ""} — ${b.severity}`);
    }
    lines.push("");
  }

  if (result.grep.missed.length > 0) {
    lines.push(
      `**${result.grep.missed.length} file(s) that grep for \`${field}\` would miss** (found via the compiler graph, not text search):`,
    );
    for (const f of result.grep.missed.slice(0, 10)) lines.push(`- \`${f}\``);
    if (result.grep.missed.length > 10) lines.push(`- … and ${result.grep.missed.length - 10} more`);
    lines.push("");
  }

  lines.push(
    "_Impact report generated by [SystemDNA](https://github.com/pujarachchh-intuitive/AIGarage). " +
      "Graph source: parser (TypeScript language service). " +
      `Renamed \`${field}\` → \`${to}\`._`,
  );
  return lines.join("\n");
}

export const MAX_DIFF = 200_000;

/** git -c option that sends the token as a header for github.com only. */
function authConfig(token: string | undefined): string[] {
  if (!token) return [];
  const basic = Buffer.from(`x-access-token:${token}`).toString("base64");
  return ["-c", `http.https://github.com/.extraheader=AUTHORIZATION: basic ${basic}`];
}

export function ownerRepo(url: string) {
  const m = url.match(/^https:\/\/github\.com\/([\w.-]+)\/([\w.-]+?)(\.git)?\/?$/);
  return m ? { owner: m[1], repo: m[2] } : null;
}

/** A script next to the scanner in core/scanner (ts-rename.mjs, ts-check.mjs). */
export function scannerTool(name: string) {
  const scanner = process.env.SYSTEMDNA_SCANNER || path.resolve(/*turbopackIgnore: true*/ process.cwd(), "../core/scanner/ts-scan.mjs");
  return path.join(/*turbopackIgnore: true*/ path.dirname(scanner), name);
}

function renamePath() {
  return scannerTool("ts-rename.mjs");
}

export async function runPullRequest(input: PullRequestInput, emit: Emit) {
  const bad = validateGitInput(input.url, input.ref);
  if (bad) throw new Error(bad);
  const target = ownerRepo(input.url);
  if (!target) throw new Error("The GitHub agent works with github.com repositories today.");
  if (!/^[A-Za-z_$][\w$]*\.[A-Za-z_$][\w$]*$/.test(input.field)) throw new Error("Only renames of a TypeScript field (Type.field) are supported today.");
  if (!/^[A-Za-z_$][\w$]*$/.test(input.to)) throw new Error("The new name must be a valid identifier.");
  if (!input.dryRun && githubMode() === "none") throw new Error(NO_CREDENTIALS);
  const renameScript = renamePath();
  if (!existsSync(renameScript)) throw new Error(`Rename agent not found at ${renameScript}.`);

  // 2. Look up the stored knowledge graph for this repo (best-effort; does not block).
  let graphImpact = "";
  try {
    const stored = await findStoredRepo(input.url, input.repoId);
    if (stored) {
      const [typeName, fieldName] = input.field.split(".");
      // Find the TSField node that matches the renamed field.
      const node = stored.graph.nodes.find(
        (n) => n.type === "TSField" && n.name === `${typeName}.${fieldName}`,
      ) ?? stored.graph.nodes.find(
        (n) => (n.type === "TSField" || n.type === "Field") && n.name.endsWith(`.${fieldName}`),
      );
      if (node) {
        const report = computeImpact(stored.graph, { node: node.id, change: "rename", to: input.to });
        graphImpact = "\n\n" + graphImpactMarkdown(input.field, input.to, report);
        emit({ type: "progress", step: "graph", detail: `Knowledge graph: ${report.items.length} components affected, ${report.waveCount} wave(s)` });
      }
    }
  } catch {
    // Graph lookup is best-effort; never block the agent.
  }

  return withWorkspace(async (dir) => {
    // 1. Clone.
    emit({ type: "progress", step: "clone", detail: `Cloning ${target.owner}/${target.repo}` });
    await cloneRepo(dir, input.url, input.ref);

    // 3 and 4. Rename and check.
    emit({ type: "progress", step: "edit", detail: `Renaming ${input.field} to ${input.to} with the TypeScript compiler` });
    let resultLine = "";
    await run(process.execPath, [renameScript, dir, "--field", input.field, "--to", input.to, "--apply"], {
      timeoutMs: LIMITS.scanMs,
      env: { NODE_OPTIONS: "--max-old-space-size=2048" },
      onLine: (l) => {
        resultLine = l;
      },
    }).catch((e: Error) => {
      // Exit code 2 = the agent refused with a reason on stdout.
      if (!resultLine) throw e;
    });
    const result = JSON.parse(resultLine || "{}") as {
      ok: boolean;
      error?: string;
      locations: number;
      stringKeys: number;
      files: { file: string; count: number }[];
      docs: { file: string; count: number }[];
      newErrors: { file: string; line: number; message: string }[];
    };
    if (result.error) throw new Error(result.error);
    if (!result.ok) {
      emit({ type: "error", message: `The rename would add ${result.newErrors.length} type errors, so nothing was changed.`, newErrors: result.newErrors });
      throw Object.assign(new Error("__reported__"), { reported: true });
    }
    emit({ type: "progress", step: "check", detail: `${result.locations} edits in ${result.files.length} code files and ${result.docs.length} docs; no new type errors` });

    // 3b. Bob Inspector (preview only; the browser adds the review to the PR body).
    if (input.dryRun) {
      emit({ type: "progress", step: "inspect", detail: "IBM Bob Inspector is reviewing the diff" });
      const [type, field] = input.field.split(".");
      const review = await inspectWithBob(
        dir,
        `Rename the field \`${input.field}\` (field \`${field}\` of type \`${type}\`) to \`${input.to}\`. The edits were made by the TypeScript compiler's rename and passed a type check.`,
        `Look for places the rename should have reached but did not: string literals, dynamic property access, JSON, config, tests, docs, SQL or API payloads that still use \`${field}\` for this type. Ignore other types that happen to have a field with the same name.`,
      );
      emit({ type: "review", review });
      emit({
        type: "progress",
        step: "inspected",
        detail:
          review.status === "done"
            ? `Bob Inspector: ${review.verdict === "approved" ? "approved" : "changes requested"}${review.issues.length ? `, ${review.issues.length} notes` : ""}`
            : `Bob Inspector skipped: ${review.reason}`,
      });
    }

    // 4. Preview.
    let diff = "";
    await run("git", ["-C", dir, "diff", "--no-color"], { timeoutMs: 60_000, onChunk: (t) => (diff += t) });
    emit({
      type: "preview",
      files: result.files,
      docs: result.docs,
      locations: result.locations,
      stringKeys: result.stringKeys,
      diff: diff.slice(0, MAX_DIFF),
      diffTruncated: diff.length > MAX_DIFF,
    });
    if (input.dryRun) {
      emit({ type: "done", dryRun: true });
      return;
    }

    // 6 and 7. Branch, commit, push, draft PR (with the knowledge-graph impact). Never the default branch.
    const pr = await pushAndOpenPr(dir, input.url, {
      ref: input.ref,
      branch: `systemdna/${input.changeId}-${input.field.split(".")[1]}-to-${input.to}`,
      title: input.title,
      commitBody: `Rename ${input.field} to ${input.to} across ${result.files.length} code files and ${result.docs.length} docs.\nMade by the SystemDNA GitHub agent with the TypeScript compiler's rename. No new type errors.`,
      body: input.body + graphImpact,
    }, emit);
    emit({ type: "done", dryRun: false, pr });
  });
}

const NO_CREDENTIALS = "Set up the GitHub App (GITHUB_APP_ID and GITHUB_APP_PRIVATE_KEY_PATH) or GITHUB_TOKEN on the server to open pull requests.";

/**
 * A fresh shallow clone into dir. The token (if any) goes in a header, never the URL.
 * Without a usable token (no app installed on the repo), public repos clone anonymously.
 */
export async function cloneRepo(dir: string, url: string, ref?: string) {
  const target = ownerRepo(url);
  const creds = target ? await credentialsFor(target.owner, target.repo).catch(() => null) : null;
  const cloneArgs = [...authConfig(creds?.token), "-c", "protocol.file.allow=never", "-c", "core.symlinks=false", "clone", "--depth", "1", "--single-branch", "--no-tags", "--quiet"];
  if (ref) cloneArgs.push("--branch", ref);
  cloneArgs.push("--", url, dir);
  await run("git", cloneArgs, { timeoutMs: LIMITS.cloneMs, env: { GIT_TERMINAL_PROMPT: "0", GIT_LFS_SKIP_SMUDGE: "1" } }).catch((e: Error) => {
    throw new Error(scrub(e.message));
  });
}

/**
 * Commits everything in dir on a new branch systemdna/..., pushes it and opens a
 * DRAFT pull request. Never touches the default branch.
 */
export async function pushAndOpenPr(
  dir: string,
  url: string,
  opts: { ref?: string; branch: string; title: string; commitBody: string; body: string },
  emit: Emit,
): Promise<{ url: string; number: number; branch: string; base: string }> {
  const target = ownerRepo(url);
  if (!target) throw new Error("The GitHub agent works with github.com repositories today.");
  // GitHub App token for this repo (throws with the install link when the app is not on it), or GITHUB_TOKEN.
  const creds = await credentialsFor(target.owner, target.repo);
  if (!creds) throw new Error(NO_CREDENTIALS);
  const branch = opts.branch.toLowerCase().replace(/[^a-z0-9/_-]+/g, "-").slice(0, 100);
  emit({ type: "progress", step: "push", detail: `Pushing branch ${branch}` });
  const repoInfo = await githubApi<{ default_branch: string; permissions?: { push?: boolean } }>(creds.token, `/repos/${target.owner}/${target.repo}`);
  if (creds.mode === "token" && repoInfo.permissions && !repoInfo.permissions.push) {
    throw new Error(`The token cannot push to ${target.owner}/${target.repo}. Give it Contents: write, or fork the repo and connect the fork.`);
  }
  const base = opts.ref || repoInfo.default_branch;
  const git = (args: string[]) => run("git", ["-C", dir, ...args], { timeoutMs: LIMITS.cloneMs, env: { GIT_TERMINAL_PROMPT: "0" } }).catch((e: Error) => {
    throw new Error(scrub(e.message));
  });
  await git(["checkout", "-b", branch]);
  await git(["add", "-A"]);
  await git([
    "-c", `user.name=${creds.author.name}`,
    "-c", `user.email=${creds.author.email}`,
    "commit", "--quiet", "--no-verify",
    "-m", opts.title,
    "-m", opts.commitBody,
  ]);
  await run("git", [...authConfig(creds.token), "-C", dir, "push", "--quiet", "origin", `HEAD:refs/heads/${branch}`], { timeoutMs: LIMITS.cloneMs, env: { GIT_TERMINAL_PROMPT: "0" } }).catch((e: Error) => {
    throw new Error(scrub(e.message));
  });
  emit({ type: "progress", step: "pr", detail: "Opening a draft pull request" });
  const pr = await githubApi<{ html_url: string; number: number }>(creds.token, `/repos/${target.owner}/${target.repo}/pulls`, {
    method: "POST",
    body: JSON.stringify({ title: opts.title, head: branch, base, body: opts.body.slice(0, 60_000), draft: true }),
  });
  return { url: pr.html_url, number: pr.number, branch, base };
}

/**
 * Asks Bob to review the edits in dir against the change. Bob is told to only
 * read; to be sure, the edits are staged first and anything Bob changes is
 * thrown away afterwards, so the diff and the PR are exactly the agents'. Never throws.
 */
export async function inspectWithBob(dir: string, change: string, focus: string, opts: { maxCost?: number } = {}): Promise<BobReview> {
  const git = (args: string[]) => run("git", ["-C", dir, ...args], { timeoutMs: 60_000, env: { GIT_TERMINAL_PROMPT: "0" } });
  let diff = "";
  try {
    await git(["add", "-A"]);
    await run("git", ["-C", dir, "diff", "--cached", "--no-color"], { timeoutMs: 60_000, onChunk: (t) => (diff += t) });
  } catch (err) {
    return { status: "skipped", reason: err instanceof Error ? err.message : "Could not read the diff" };
  }
  const task = `# SystemDNA Inspector task

You are the Inspector agent of SystemDNA. Review a change that was already made in this repository.

- Change: ${change}
- The staged diff is below. You may read any file in this folder to check it.

Rules:
- Do NOT edit, create or delete any file. Do NOT run commands that change files. Only read.
- ${focus}
- Do not include \`${TASK_FILE}\` in your answer.

Reply with ONLY this JSON, no other text:
{"verdict": "approved" | "changes_requested", "summary": "one or two sentences", "issues": [{"file": "path", "line": 0, "message": "what is missed or wrong"}]}

Use "approved" when nothing is missed. Keep at most 10 issues.

## Staged diff

\`\`\`diff
${diff.slice(0, 60_000)}
\`\`\`
`;
  const result = await runBob(dir, task, opts.maxCost ? { maxCost: opts.maxCost } : {});
  // Throw away anything Bob changed, then unstage so later steps see the same tree.
  await git(["checkout", "--", "."]).catch(() => {});
  await git(["clean", "-fdxq"]).catch(() => {});
  await git(["reset", "-q"]).catch(() => {});
  if (!result.ok) return { status: "skipped", reason: result.error ?? "Bob did not finish" };
  const parsed = extractJson<{ verdict?: string; summary?: string; issues?: { file?: string; line?: number; message?: string }[] }>(result.lastMessage);
  if (!parsed) return { status: "skipped", reason: "Bob's answer was not valid JSON" };
  return {
    status: "done",
    verdict: parsed.verdict === "approved" ? "approved" : "changes_requested",
    summary: scrubBob(String(parsed.summary ?? "")).slice(0, 600),
    issues: (parsed.issues ?? [])
      .filter((i) => i && i.message)
      .slice(0, 10)
      .map((i) => ({ file: String(i.file ?? "").slice(0, 300), line: Number(i.line) || undefined, message: scrubBob(String(i.message)).slice(0, 400) })),
    bobcoins: result.bobcoins,
    durationMs: result.durationMs,
  };
}

/** Streams agent events as newline-delimited JSON. */
export function agentStream(input: PullRequestInput): Response {
  const encoder = new TextEncoder();
  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      const emit: Emit = (e) => controller.enqueue(encoder.encode(JSON.stringify(e) + "\n"));
      try {
        await runPullRequest(input, emit);
      } catch (err) {
        if (!(err as { reported?: boolean }).reported) emit({ type: "error", message: scrub(err instanceof Error ? err.message : "Something went wrong") });
      } finally {
        controller.close();
      }
    },
  });
  return new Response(stream, { headers: { "Content-Type": "application/x-ndjson; charset=utf-8", "Cache-Control": "no-store" } });
}
